Fix ArgumentError on Ruby 3.2/kwargs/ActionMailer
Ruby 3.2's `super` recognize kwargs only if declared arguments separately for ActionMailer method call.

Or we get error below:
```
ArgumentError: wrong number of arguments (given 1, expected 0; required keyword: subject)
```